services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend